export const diploma_colleges = [
  "Adarsha College Of Engneering",
  "Adarsha Institute Of Technology & Management",
  "Amaravati Polytechnic",
  "Aryan Inst. Of Engg. & Tech. Poly",
  "Aryan Institute Of Engineering & Technology",
  "Asian School Of Tech.",
  "Aumsai Institute Of Technical Educationpoly",
  "B.I.T. Polytechnic",
  "Badri Prasad Inst. Of Tech.",
  "Bajirout Inst. Of Eng. & Tech. (Poly)",
  "Balaji Inst. Of Tech. & Science",
  "Balasore School Of Engineering",
  "Barapada School Of Engg. & Tech.",
  "Barunei Inst. Of Engg. & Tech.Poly",
  "Berhampur School Of Engg. & Technology",
  "Bhadrak Engg. School & Tech.",
  "Bharat Inst. Of Engg. & Tech., Sivram Vihar",
  "Bhubananada Orissa School Of Engg",
  "Bhubaneswar Engineering College",
  "Bhubaneswar Institute Of Industrial Technology",
  "Biju Patnaik Inst. Of Technology",
  "Government Polytechnic, Puri",
  "Black Diamond School Of Engineering",
  "C.V. Raman Polytechnic",
  "Capital Engineering College",
  "City Inst.Of Technical Education",
  "College Of Engineering",
  "Dhabaleswar Institute Of Polytechnic",
  "Divine Institute Of Engg. & Tech.",
  "Driems Polytechnic",
  "Eastern Academy Of Science & Technology",
  "Einstein Academy Of Tech. & Mgmt",
  "Einstein School Of Engg.",
  "Ganapati Inst. Of Engg. & Tech.Poly",
  "Gandhi Academy Of Technology Engineering",
  "Gandhi Engg. College (Gec)",
  "Gandhi Inst. For Edn. & Tech.",
  "Gandhi Institute Of Advanced Compuer & Research",
  "Gandhi Institute Of Excellent Technocrats",
  "Gandhi Institute Of Science & Technology",
  "Gandhi Institute Of Tech. & Mgmt. (Gitam)",
  "Gandhi School Of Engg.",
  "Ganesh Institute Of Engg. & Tech.Poly",
  "Gift Autonomous",
  "Govt. Polytechnic, Angul",
  "Govt. Polytechnic, Balangir",
  "Govt. Polytechnic, Balasore",
  "Govt. Polytechnic, Bargarh",
  "Govt. Polytechnic, Berhampur",
  "Govt. Polytechnic, Bhubaneswar",
  "Govt. Polytechnic, Boudh",
  "Govt. Polytechnic, Deogarh",
  "Govt. Polytechnic, Dhenkanal",
  "Govt. Polytechnic, Gajapati",
  "Govt. Polytechnic, Jagatsinghpur",
  "Govt. Polytechnic, Jajpur",
  "Govt. Polytechnic, Kandhamal",
  "Govt. Polytechnic, Kendrapada",
  "Govt. Polytechnic, Koraput",
  "Govt. Polytechnic, Malkanagiri",
  "Govt. Polytechnic, Mayurbhanj, Tikarpada",
  "Govt. Polytechnic, Nawarangpur",
  "Govt. Polytechnic, Nayagarh",
  "Govt. Polytechnic, Nuapada",
  "Govt. Polytechnic, Sambalpur",
  "Govt. Polytechnic, Sonepur",
  "Gurukrupa Technical School",
  "Gurukula Engg School",
  "Hi-Tech Institute Of Techn.",
  "Hi-Tech. Institute Of Engg. & Mgmt.",
  "Hi-Tech. Institute Of Inf. & Tech.",
  "Holy Institute Of Technology",
  "Ideal School Of Engg Poly",
  "Iipm School Of Engineering & Technology",
  "Indic Institute Of Design & Research",
  "Indira Gandhi Institute Of Tech.",
  "Indotech College Of Engg.",
  "Indus School Of Engg.",
  "Inst. Of Textile Technology",
  "Institute Of Engg. & Mgmt.",
  "International Polytechnic",
  "Jeypore School Of Engg. & Tech.",
  "Jhadeswar Inst. Of Engg. & Tech.",
  "Jharsuguda Engineering School",
  "Kalam Institute Of Technology",
  "Kalinga Inst. Of Engg. & Technology",
  "Kalinga Nagar Polytechnic",
  "Keonjhar School Of Engineering",
  "Kiit Polytechnic",
  "Krupajal Engineering School",
  "Mahalaxmi Institute Of Tech. & Engg.",
  "Mahamaya Inst. Of Medical & Tech.",
  "Maharaja Institute Of Advanced Computing And Research",
  "Mahavir Engineering College",
  "Mayurbhanj School Of Engineering",
  "Mits School Of Engineering",
  "Nalanda Institute Of Tech.",
  "Narayani Inst. Of Engg. & Technology",
  "Nayagarh Institute Of Engineering & Technology(Polytechnic)",
  "Nigam Institute Of Engineering & Technology",
  "Niis Institute Of Engineering & Technology",
  "Nilachal Polytechnic",
  "Nilasaila Institute Of Science &Tech.",
  "Nm Institute Of Engg. & Technology",
  "North Odisha School Of Engg.",
  "Odisha Polytechnic",
  "Orissa Institute Of Engg. & Technology",
  "Orissa School Of Engineeringpoly",
  "Orissa School Of Mining Engineering",
  "Oxford College Of Engg. & Manangement",
  "Oxford School Of Polytechnic Diploma",
  "Pabitra Mohan Institute Of Technology",
  "Padmashree Krutartha Acharya Inst. Of Eng. & Tech.",
  "Pathani Samanta Institute Of Engg. & Tech. Poly",
  "Pns School Of Engg. & Tech. Marsaghai",
  "Purna Chandra Inst. Of Engg. & Technology",
  "Purusottam School Of Engg. & Tech. Poly",
  "Raja Kishore Chandra Academy Of Tech.",
  "Rajdhani Engg. College",
  "Ramarani Institute Of Technology",
  "Rayagada Institute Of Technology & Mgt",
  "Rk Institute Of Engg. & Tech.",
  "Rourkela Institute Of Tech.",
  "Sai Institute Of Tech.",
  "Sai School Of Engineering",
  "Sakuntala Sudarsan Inst. Of Tech.",
  "Samanta Chandra Sekhar Inst. Of Tech. & Mgt.",
  "Sanjay Memorial Institute Of Tech.",
  "Satya Sai School Of Engg.",
  "Seemanta Engg. College",
  "Siddhartha Institute Of Engg. & Tech.",
  "Skdav Govt. Polytechnic",
  "Soro School Of Engineering",
  "Spintronic Technology & Advance Research",
  "Sri Polytechnic",
  "Ssb Regional Inst. Of Sc. & Tech. Poly",
  "Suddhananda Residential Polytechnic",
  "Sudhananda Engineering & Research Centre",
  "Sundergarh Engineering School",
  "Sushree Institute Of Tech. Education",
  "Swami Vivekananda School Of Engg. & Tech. Poly",
  "Synergy Polytechnic",
  "Synergy School Of Engineering",
  "Temple City Inst. Of Technology & Engg.",
  "The Techno School",
  "Uma Charan Patnaik Engg. School",
  "Utkal Gourab Madhusudan Inst. Of Technology",
  "Utkal Institute Of Engg. & Tech.",
  "Utkalmani Gopabandhu Inst. Of Engg",
  "Vedang Institute Of Tech",
  "Venus Group Of Educational & Reaserch Institute",
  "Vijayanjali School Of Engineering",
  "Vikash Polytechnic",
  "Zenith Institute Of Science & Technology",
];
